# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    halku_jtc:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

halku_jtc:
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity