controller_manager:
  ros__parameters:
    update_rate: 20

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
      - link_3_joint
      - link_4_joint
      # - link_5_joint
      # - link_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity