"""Abstract base class for LLM backends."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# works as a lightweight custom data strcuture
# @dataclass acts as a decorator which automatically generates some boilerplate code like __init__ and repr, eq etc.,
@dataclass
class ToolCall:
    """Represents a single tool call from the LLM."""
    name: str # Stores the tool name
    args: Dict[str, Any] # Stores the parameters generated by LLM
    id: str = ""  # Some APIs return a call ID for tracking


@dataclass
class LLMResponse:
    """Standard response from any LLM backend."""
    text: Optional[str] = None # Stores conversational text if any
    tool_calls: List[ToolCall] = field(default_factory=list) # stores the list of tool_calls provided by the LLM # for deafult param field is used to provide fresh list each time
    reasoning_details: Any = None # stores reasoning steps if in future some model provides

    # returns true if tool call list is empty or has one or more tool_calls
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0

# ABC inside the brackets shows this class is Abstract Base Class It tells python that this class cannot be intialized directly it need to be inherited
class BaseLLMBackend(ABC):
    """
    Abstract interface for LLM providers.
    
    All backends must implement chat() which:
    1. Accepts a message history and tool definitions
    2. Returns an LLMResponse with either text or tool_calls
    """

    # Decorater it makes all child class to make sure define the chat() method of it's own
    @abstractmethod
    def chat(self, messages: list, tools: list) -> LLMResponse:
        """
        Send a chat request to the LLM.
        
        Args:
            messages: List of message dicts with 'role' and 'content'/'parts'
            tools: List of tool function declarations
            
        Returns:
            LLMResponse with either text or tool_calls
        """
        pass
