"""Groq LLM backend with tool calling support."""

import os
import json
from typing import List

from hulku_ai_agent.llm_backends.base_backend import BaseLLMBackend, LLMResponse, ToolCall


class GroqBackend(BaseLLMBackend):
    """
    Groq backend using the Groq Python SDK with tool calling.
    Fast inference with models like llama-3.1-70b-versatile.
    
    API key resolution order:
        1. GROQ_API_KEY environment variable
        2. Explicitly passed api_key parameter
    """

    # Intialize with the configuration from yaml and env file
    def __init__(self, model_name: str = "llama-3.1-70b-versatile", api_key: str = None):
        self._model_name = model_name
        self._api_key = api_key or os.environ.get("GROQ_API_KEY", "")

        if not self._api_key:
            raise ValueError(
                "Groq API key not found. Set GROQ_API_KEY env var "
                "or pass api_key parameter."
            )

        # below comment is not ask pyrefly to ignore this missing-import error
        # pyrefly: ignore [missing-import]
        from groq import Groq
        self._client = Groq(api_key=self._api_key)

    # converting list of tool dict into Groq's tool dict format (Almost no change)
    def _convert_tools(self, tools: list) -> list:
        """Convert our tool definitions to OpenAI-compatible format used by Groq."""
        groq_tools = []
        for tool in tools:
            groq_tools.append({
                "type": "function",
                "function": {
                    "name": tool["name"],
                    "description": tool["description"],
                    "parameters": tool["parameters"],
                }
            })
        return groq_tools


    def chat(self, messages: list, tools: list) -> LLMResponse:
        # Convert messages to Groq/OpenAI format
        # Initialize empty list for groq formatted messages
        groq_messages = []
        for msg in messages:
            role = msg["role"]
            # If it is a tool result message then convert it into Groq format
            if role == "tool_result":
                groq_messages.append({
                    "role": "tool",
                    "content": msg["content"],
                    "tool_call_id": msg.get("tool_call_id", ""),
                    "name": msg.get("tool_name", ""),
                })
            # for other messages just copy the same
            else:
                out_msg = {
                    "role": role,
                    "content": msg["content"],
                }
                # Here we check tool_calls so that we can add tool call result if done by assistant in past
                if "tool_calls" in msg:
                    out_msg["tool_calls"] = msg["tool_calls"]
                groq_messages.append(out_msg)

        kwargs = {
            "model": self._model_name,
            "messages": groq_messages,
            "temperature": 0.1, # taken 0.1 so it remain deterministic and don't hallucinate
        }

        # if tools then provide it to the model
        if tools:
            kwargs["tools"] = self._convert_tools(tools)
            # tool choice auto gives LLM freedom to decide whether to use tool or respond with normal speech
            kwargs["tool_choice"] = "auto"
            # NOTE: Uncheck if needed for parallel tool calls disable if it cause problem with tool calls
            # kwargs["parallel_tool_calls"] = False

        try:
            # sends request to groq's cloud server for inference with the configuration and query
            response = self._client.chat.completions.create(**kwargs)
        except Exception as e:
            return LLMResponse(text=f"Error calling Groq: {str(e)}")

        # gets the top response generated by the model
        choice = response.choices[0]
        message = choice.message

        tool_calls = []
        # if tool calls are present then extract them and append to tool_calls list
        if message.tool_calls:
            for tc in message.tool_calls:
                args = json.loads(tc.function.arguments) if tc.function.arguments else {}
                tool_calls.append(ToolCall(
                    name=tc.function.name,
                    args=args,
                    id=tc.id or "",
                ))

        # returns the response in LLMResponse format
        return LLMResponse(
            text=message.content if message.content else None,
            tool_calls=tool_calls,
        )
